# SNS
sns_topic_name_notification_request_creation="notification-request-creation-topic"
sns_topic_name_notification_request_update="notification-request-update-topic"

# SQS
sqs_queue_name_notification_request_creation="notification-request-creation"
sqs_queue_name_notification_request_creation_deadletter="notification-request-creation-deadletter"
